### ISSUE TITLE
After created a new scheduled message, main screen won't update immediately to reflect the change.

### ISSUE THREAD

**Issue by Haocen** [jordond/hooold#9]
Not sure what had caused this.
My device is HTC A9 with Android 6.0 .

It would be great to implement basic Android crash report, so we can help you do real device debugging.
Thanks for your great work.

**Comment by jordond** [comment]
Yes sorry that bug went unchanged for so long... I built this app as a side project mainly just for my use.  And I haven't spent the time to really make this app what I want it to be.  I originally intended for it to be much more feature rich.

That being said I haven't abandoned the project, in fact I fixed this bug with this commit 9deeeda yesterday and published an update to the app store.  It should be available any time now.

If for whatever reason it's not then you can download the latest apk from [here](https://ci.hoogit.ca/job/Hooold.master/).

The fix I implemented was very much just a quick fix, I plan on fixing it properly soon.

**Comment by Haocen** [comment]
Thanks.
